// SPDX-License-Identifier: MIT
pragma solidity =0.8.28;

/**
 * @title MerkleTree
 * @dev Verifies Merkle Roots generated by the Rust `MerkleTree` implementation.
 *
 * Logic Alignment with Rust:
 * 1. Leaves are padded to the next power of two with zero hashes (bytes32(0)).
 * 2. Internal nodes are computed as: keccak256(abi.encodePacked(0x01, left, right)).
 * 3. No sorting is performed on leaves; order is preserved as inserted.
 */
library MerkleTree {
    /// @dev Prefix byte to distinguish internal nodes from leaves (matches Rust INNER_NODE_PREFIX)
    uint8 private constant INNER_NODE_PREFIX = 0x01;

    /// @dev Empty leaf used for padding to power of two
    bytes32 private constant EMPTY_LEAF = 0x0000000000000000000000000000000000000000000000000000000000000000;

    /**
     * @notice Computes the Merkle Root from an array of leaves.
     * @dev This function replicates the Rust logic:
     *      1. Pads leaves to the next power of two.
     *      2. Iteratively hashes pairs from bottom to top.
     * @param leaves The array of leaf hashes (roots submitted by users).
     * @return root The calculated Merkle Root.
     */
    function computeRoot(bytes32[] memory leaves) internal pure returns (bytes32 root) {
        uint256 count = leaves.length;
        require(count > 0, "Merkle: Cannot compute root of empty set");

        if (count == 1) {
            return leaves[0];
        }

        uint256 width = nextPowerOfTwo(count);
        uint256 halfWidth = width / 2;

        bytes32[] memory buffer = new bytes32[](halfWidth);

        uint256 fullPairs = count / 2;

        // 1. Handle full pairs of leaves
        for (uint256 i = 0; i < fullPairs; i++) {
            buffer[i] = hashNode(leaves[i * 2], leaves[i * 2 + 1]);
        }

        // 2. May have an odd leaf left, which pairs with an empty leaf
        if (count % 2 != 0) {
            buffer[fullPairs] = hashNode(leaves[count - 1], bytes32(0));
            for (uint256 i = fullPairs + 1; i < halfWidth; i++) {
                buffer[i] = hashNode(bytes32(0), bytes32(0));
            }
        } else {
            for (uint256 i = fullPairs; i < halfWidth; i++) {
                buffer[i] = hashNode(bytes32(0), bytes32(0));
            }
        }

        // 3. Iteratively compute upper levels in-place within the buffer
        uint256 currentLevelSize = halfWidth;
        while (currentLevelSize > 1) {
            currentLevelSize /= 2;
            for (uint256 i = 0; i < currentLevelSize; i++) {
                buffer[i] = hashNode(buffer[i * 2], buffer[i * 2 + 1]);
            }
        }

        return buffer[0];
    }

    /**
     * @notice Verifies if a set of leaves corresponds to a given root.
     * @param leaves The array of leaf hashes.
     * @param expectedRoot The expected Merkle Root.
     * @return valid True if the calculated root matches the expected root.
     */
    function verify(bytes32[] memory leaves, bytes32 expectedRoot) internal pure returns (bool valid) {
        return computeRoot(leaves) == expectedRoot;
    }

    /**
     * @dev Internal function to hash two child nodes into a parent node.
     *      Matches Rust: Digest::update(&mut hasher, [INNER_NODE_PREFIX]); ...
     */
    function hashNode(bytes32 left, bytes32 right) public pure returns (bytes32) {
        // Clean Assembly Implementation for _hashNode
        bytes32 result;
        assembly ("memory-safe") {
            let ptr := mload(0x40)
            mstore8(ptr, INNER_NODE_PREFIX)
            mstore(add(ptr, 1), left)
            mstore(add(ptr, 33), right)
            result := keccak256(ptr, 65)
        }
        return result;
    }

    /**
     * @dev Calculates the next power of two greater than or equal to n.
     */
    function nextPowerOfTwo(uint256 n) public pure returns (uint256) {
        if (n == 0) return 1;
        n--;
        n |= n >> 1;
        n |= n >> 2;
        n |= n >> 4;
        n |= n >> 8;
        n |= n >> 16;
        n |= n >> 32;
        n |= n >> 64;
        n |= n >> 128;
        n++;
        return n;
    }
}
