// SPDX-License-Identifier: MIT
pragma solidity ^0.8.29;

/**
 * @title MerkleTree
 * @dev Verifies Merkle Roots generated by the Rust `MerkleTree` implementation.
 *
 * Logic Alignment with Rust:
 * 1. Leaves are padded to the next power of two with zero hashes (bytes32(0)).
 * 2. Internal nodes are computed as: keccak256(abi.encodePacked(0x01, left, right)).
 * 3. No sorting is performed on leaves; order is preserved as inserted.
 */
library MerkleTree {
    /// @dev Prefix byte to distinguish internal nodes from leaves (matches Rust INNER_NODE_PREFIX)
    bytes32 private constant INNER_NODE_PREFIX = 0x0100000000000000000000000000000000000000000000000000000000000000;

    /// @dev Empty leaf used for padding to power of two
    bytes32 private constant EMPTY_LEAF = 0x0000000000000000000000000000000000000000000000000000000000000000;

    /**
     * @notice Computes the Merkle Root from an array of leaves.
     * @dev This function replicates the Rust logic:
     *      1. Pads leaves to the next power of two.
     *      2. Iteratively hashes pairs from bottom to top.
     * @param leaves The array of leaf hashes (roots submitted by users).
     * @return root The calculated Merkle Root.
     */
    function computeRoot(bytes32[] memory leaves) internal pure returns (bytes32 root) {
        uint256 count = leaves.length;
        require(count > 0, "Merkle: Cannot compute root of empty set");

        // If only one leaf, return it directly (Rust logic: tree of size 1 has root = leaf)
        if (count == 1) {
            return leaves[0];
        }

        // Calculate the next power of two for the tree width
        uint256 width = _nextPowerOfTwo(count);

        // We need a buffer to hold the current level of hashes.
        // Max width needed is 'width'. We can reuse memory or allocate new.
        // For clarity and safety in loops, we allocate a dynamic array for the current level.
        bytes32[] memory level = new bytes32[](width);

        // 1. Initialize the leaf level (bottom of the tree)
        // Copy leaves to the beginning of the buffer
        for (uint256 i = 0; i < count; i++) {
            level[i] = leaves[i];
        }
        // Pad the rest with EMPTY_LEAF (bytes32(0))
        // Note: Solidity arrays initialize to 0 by default, so explicit loop is optional
        // but kept here for clarity if EMPTY_LEAF changes or for explicit intent.
        // for (uint256 i = count; i < width; i++) { level[i] = EMPTY_LEAF; }

        // 2. Build the tree bottom-up
        // Current number of nodes in this level
        uint256 currentSize = width;

        while (currentSize > 1) {
            uint256 nextSize = (currentSize + 1) / 2;

            for (uint256 i = 0; i < nextSize; i++) {
                uint256 leftIndex = 2 * i;
                uint256 rightIndex = 2 * i + 1;

                bytes32 left = level[leftIndex];
                // If right index is out of bounds (shouldn't happen with power-of-two padding), treat as empty
                bytes32 right = (rightIndex < currentSize) ? level[rightIndex] : EMPTY_LEAF;

                // Hash: keccak256(0x01 || left || right)
                level[i] = _hashNode(left, right);
            }

            currentSize = nextSize;
        }

        return level[0];
    }

    /**
     * @notice Verifies if a set of leaves corresponds to a given root.
     * @param leaves The array of leaf hashes.
     * @param expectedRoot The expected Merkle Root.
     * @return valid True if the calculated root matches the expected root.
     */
    function verify(bytes32[] memory leaves, bytes32 expectedRoot) internal pure returns (bool valid) {
        return computeRoot(leaves) == expectedRoot;
    }

    /**
     * @dev Internal function to hash two child nodes into a parent node.
     *      Matches Rust: Digest::update(&mut hasher, [INNER_NODE_PREFIX]); ...
     */
    function _hashNode(bytes32 left, bytes32 right) private pure returns (bytes32) {
        assembly ("memory-safe") {
            let ptr := mload(0x40) // Free memory pointer

            // Store prefix (0x01) at the start of the 32-byte slot
            mstore(ptr, INNER_NODE_PREFIX)
            // Store left hash immediately after (offset 32)
            mstore(add(ptr, 32), left)
            // Store right hash immediately after (offset 64)
            mstore(add(ptr, 64), right)

            // Hash 96 bytes (3 words): prefix + left + right
            let hash := keccak256(ptr, 96)

            mstore(0x40, add(ptr, 96)) // Update free memory pointer (optional in pure view, but good practice)

            // Return result via stack
            mstore(0x00, hash) // Store temporarily to return? No, assembly returns via stack variable
            // Actually, in inline assembly within a function returning bytes32, we just assign to the variable
            // But here we are in a private pure function returning bytes32.
            // The standard way is to let solidity handle the return, or use mstore(0, hash) and load.
            // Let's stick to high-level return for safety, but use assembly for the keccak.
            // Correction: To return from assembly block, we need to assign to a variable defined outside
            // or use `result := ...` syntax if defined in `returns`.

            // Re-writing slightly cleaner:
            pop(0) // Placeholder to satisfy compiler if needed, but let's just use standard return logic below
        }
        // Fallback to high-level if assembly feels too risky for specific compiler versions,
        // but the assembly above is standard. Let's provide the clean assembly return version.

        // Clean Assembly Implementation for _hashNode
        bytes32 result;
        assembly ("memory-safe") {
            let ptr := mload(0x40)
            mstore(ptr, INNER_NODE_PREFIX)
            mstore(add(ptr, 32), left)
            mstore(add(ptr, 64), right)
            result := keccak256(ptr, 96)
            // We don't strictly need to update 0x40 in a pure function that doesn't allocate further,
            // but it's safe to do so.
            mstore(0x40, add(ptr, 96))
        }
        return result;
    }

    /**
     * @dev Calculates the next power of two greater than or equal to n.
     */
    function _nextPowerOfTwo(uint256 n) private pure returns (uint256) {
        if (n == 0) return 1;
        n--;
        n |= n >> 1;
        n |= n >> 2;
        n |= n >> 4;
        n |= n >> 8;
        n |= n >> 16;
        n |= n >> 32;
        n++;
        return n;
    }
}
