# packages/sdk-py/src/uts_sdk/__init__.py
"""Universal Timestamps Python SDK."""

from __future__ import annotations

from uts_sdk._codec import Decoder, Encoder
from uts_sdk._crypto import MerkleProof, SiblingNode, UnorderedMerkleTree, keccak256, sha256
from uts_sdk._types import (
    AppendStep,
    Attestation,
    AttestationStatus,
    AttestationStatusKind,
    AttestationStep,
    BitcoinAttestation,
    DetachedTimestamp,
    DigestHeader,
    DigestOp,
    EASTimestamped,
    EASAttestation,
    ForkStep,
    HexlifyStep,
    Keccak256Step,
    NodePosition,
    OpCode,
    PendingAttestation,
    PrependStep,
    RIPEMD160Step,
    ReverseStep,
    SHA1Step,
    SHA256Step,
    StampPhase,
    Step,
    Timestamp,
    UnknownAttestation,
    UpgradeResult,
    UpgradeStatus,
    VerifyStatus,
)
from uts_sdk.errors import DecodeError, EncodeError, RemoteError, UTSError, VerifyError
from uts_sdk.sdk import SDK, VerificationResult

__version__ = "0.1.0"

__all__ = [
    "SDK",
    "VerificationResult",
    "OpCode",
    "Attestation",
    "PendingAttestation",
    "BitcoinAttestation",
    "EASAttestation",
    "EASTimestamped",
    "UnknownAttestation",
    "Timestamp",
    "Step",
    "DetachedTimestamp",
    "DigestHeader",
    "DigestOp",
    "VerifyStatus",
    "AttestationStatus",
    "AttestationStatusKind",
    "UpgradeStatus",
    "UpgradeResult",
    "StampPhase",
    "NodePosition",
    "AttestationStep",
    "AppendStep",
    "PrependStep",
    "SHA256Step",
    "SHA1Step",
    "RIPEMD160Step",
    "Keccak256Step",
    "ReverseStep",
    "HexlifyStep",
    "ForkStep",
    "Encoder",
    "Decoder",
    "UnorderedMerkleTree",
    "MerkleProof",
    "SiblingNode",
    "sha256",
    "keccak256",
    "UTSError",
    "EncodeError",
    "DecodeError",
    "RemoteError",
    "VerifyError",
]
